import { Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { onboardingSlides } from "../data";
import { colors } from "../theme";

export default function OnboardingScreen({ index, onSkip, onNext }: { index: number; onSkip: () => void; onNext: () => void }) {
  const slide = onboardingSlides[index];
  return <SafeAreaView style={styles.container}><Pressable onPress={onSkip} style={styles.skip}><Text style={styles.link}>Pular</Text></Pressable><View style={styles.body}><View style={[styles.card, { backgroundColor: slide.color }]}><Text style={styles.kanji}>{slide.character}</Text></View><Text style={styles.title}>{slide.title}</Text><Text style={styles.copy}>{slide.text}</Text><View style={styles.dots}>{onboardingSlides.map((_, dot) => <View key={dot} style={[styles.dot, dot === index && styles.active]} />)}</View><Pressable onPress={onNext} style={styles.button}><Text style={styles.buttonText}>{index === onboardingSlides.length - 1 ? "Começar" : "Próximo"}</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { backgroundColor: colors.bg, flex: 1, padding: 20 }, skip: { alignSelf: "flex-end", padding: 8 }, link: { color: colors.primary, fontWeight: "700" }, body: { alignItems: "center", flex: 1, justifyContent: "center" }, card: { alignItems: "center", borderRadius: 28, height: 200, justifyContent: "center", marginBottom: 32, width: 200 }, kanji: { color: colors.surface, fontSize: 110 }, title: { color: colors.text, fontSize: 26, fontWeight: "700", textAlign: "center" }, copy: { color: colors.secondaryText, fontSize: 15, lineHeight: 22, marginTop: 10, textAlign: "center" }, dots: { flexDirection: "row", gap: 8, marginTop: 30 }, dot: { backgroundColor: colors.border, borderRadius: 4, height: 8, width: 8 }, active: { backgroundColor: colors.primary, width: 24 }, button: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 12, justifyContent: "center", marginTop: 28, minHeight: 52, width: "100%" }, buttonText: { color: colors.surface, fontSize: 16, fontWeight: "700" } });
